### ISSUE TITLE
Allow creation of "pubrundor " 

### ISSUE THREAD

**Issue by Frewacom** [nationskollen/server#151]
You should be able to create a "pubrunda" by selecting an arbitrary amount of locations (for any nation) and select which order they should be listed in. When created you should be able to fetch it and eventually display it in the map of the app. Since each location has coordinates, this should be enough information to construct the route in the front end.

### TODO
- [ ] Extend the Event model with a new optional relation for "Visits"
- [ ] Add a new model for a "visit" during a pubrunda
    - [ ] Visit order (e.g. a value of 2 means that is the second pub that will be visited, etc)
    - [ ] Reference to a location (for any nation)
    - [ ] Estimated time of arrival
- [ ] Add routes for creating, deleting and updating "Visits"
- [ ] Add new category for "Pubrunda"
- [ ] Assigning an event to the "Pubrunda" category will require a route (collection of visits)
